// Generated by CoffeeScript 1.6.3
(function() {
  var handlers, update, _chromosomeIndex, _tetris;

  importScripts('tetris.js', '/libraries/underscore.js');

  _tetris = _chromosomeIndex = null;

  update = function() {
    if (!_tetris.gameOver()) {
      _tetris.makeMove();
      return self.postMessage({
        func: 'move',
        tetris: _tetris,
        index: _chromosomeIndex
      });
    } else {
      self.postMessage({
        func: 'complete',
        score: _tetris.score,
        index: _chromosomeIndex
      });
      return self.close();
    }
  };

  handlers = {
    evaluateFitness: function() {
      var chromosome, chromosomeIndex, index, workerIndex, _ref;
      _ref = e.data, chromosome = _ref.chromosome, index = _ref.index;
      workerIndex = index.workerIndex, chromosomeIndex = index.chromosomeIndex;
      _tetris = new TetrisAI(chromosome.genes);
      _chromosomeIndex = chromosomeIndex;
      return update();
    },
    update: function() {
      return update();
    }
  };

  self.addEventListener('message', function(e) {
    return handlers[e.data.func]();
  });

}).call(this);
